# travis-ci test main source and push to mirrors

language: bash
sudo: enabled

jobs:
  include:
    - os: linux
      dist: focal
      before_install: sudo apt-get update

install:
  - sudo bash -c "$(curl -LSs https://github.com/systemmgr/installer/raw/main/install.sh)" && systemmgr install installer
  - systemmgr install nginx
  - sudo systemctl status nginx

notifications:
  email:
    on_failure: never
    on_success: never
